-- Additional Leader bindings for WhichKey
-- O.user_which_key = {
--     A = {
--         name = "+Custom Leader Keys",
--         a = {"<cmd>echo 'first custom command'<cr>", "Description for a"},
--         b = {"<cmd>echo 'second custom command'<cr>", "Description for b"}
--     }
-- }
